=== Foxy/foxy-elements/src/static/schemas/access-recovery-form.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "properties": {
    "email": {
      "default": "Email",
      "type": "string"
    },
    "recover_access": {
      "default": "Get temporary password",
      "type": "string"
    },
    "recover_access_success": {
      "default": "Done! Please check your email for further instructions.",
      "type": "string"
    },
    "spinner": {
      "properties": {
        "loading_busy": {
          "$ref": "spinner.json#/properties/loading_busy"
        },
        "loading_error": {
          "$ref": "spinner.json#/properties/loading_error"
        }
      },
      "required": ["loading_busy", "loading_error"],
      "additionalProperties": false
    },
    "unknown_error": {
      "default": "An unknown error has occured. Please try again later.",
      "type": "string"
    },
    "v8n_invalid_email": {
      "default": "Invalid email",
      "type": "string"
    },
    "v8n_required": {
      "default": "Required",
      "type": "string"
    }
  },
  "required": [
    "email",
    "recover_access",
    "recover_access_success",
    "unknown_error",
    "v8n_invalid_email",
    "v8n_required",
    "spinner"
  ],
  "additionalProperties": false
}

=== Foxy/foxy-elements/src/static/translations/access-recovery-form/en.json
{
  "email": "Email",
  "recover_access": "Get temporary password",
  "recover_access_success": "Done! Please check your email for further instructions.",
  "unknown_error": "An unknown error has occured. Please try again later.",
  "v8n_invalid_email": "Invalid email",
  "v8n_required": "Required",
  "spinner": {
    "loading_busy": "Loading",
    "loading_error": "Failed to load"
  }
}
