=== Foxy/foxy-elements/src/static/schemas/address-form.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "additionalProperties": false,
  "properties": {
    "address_name": { "type": "string", "default": "Address name" },
    "address1": { "type": "string", "default": "Address Line 1" },
    "address2": { "type": "string", "default": "Address Line 2" },
    "cancel": { "type": "string", "default": "Cancel" },
    "city": { "type": "string", "default": "City" },
    "company": { "type": "string", "default": "Company" },
    "confirm": { "type": "string", "default": "Confirm" },
    "country": { "type": "string", "default": "Country" },
    "create": { "type": "string", "default": "Create" },
    "date": { "type": "string", "default": "{{value, date}}" },
    "date_created": { "type": "string", "default": "Created on" },
    "date_modified": { "type": "string", "default": "Last updated" },
    "delete": { "type": "string", "default": "Delete" },
    "delete_prompt": {
      "type": "string",
      "default": "This resource will be permanently removed. Are you sure?"
    },
    "first_name": { "type": "string", "default": "First name" },
    "last_name": { "type": "string", "default": "Last name" },
    "phone": { "type": "string", "default": "Phone" },
    "postal_code": { "type": "string", "default": "Postal code" },
    "region": { "type": "string", "default": "Region" },
    "v8n_required": { "type": "string", "default": "Required" },
    "v8n_too_long": { "type": "string", "default": "Too long" },
    "spinner": {
      "additionalProperties": false,
      "properties": {
        "loading_busy": { "type": "string", "default": "Loading" },
        "loading_error": { "type": "string", "default": "Failed to load" }
      },
      "required": ["loading_busy", "loading_error"]
    }
  },
  "required": [
    "address_name",
    "address1",
    "address2",
    "cancel",
    "city",
    "company",
    "confirm",
    "country",
    "create",
    "date",
    "date_created",
    "date_modified",
    "delete",
    "delete_prompt",
    "first_name",
    "last_name",
    "phone",
    "postal_code",
    "region",
    "v8n_required",
    "v8n_too_long",
    "spinner"
  ]
}

=== Foxy/foxy-elements/src/static/translations/address-form/en.json
{
  "address_name": "Address name",
  "address1": "Address Line 1",
  "address2": "Address Line 2",
  "cancel": "Cancel",
  "city": "City",
  "company": "Company",
  "confirm": "Confirm",
  "country": "Country",
  "create": "Create",
  "date": "{{value, date}}",
  "date_created": "Created on",
  "date_modified": "Last updated",
  "delete": "Delete",
  "delete_prompt": "This resource will be permanently removed. Are you sure?",
  "first_name": "First name",
  "last_name": "Last name",
  "phone": "Phone",
  "postal_code": "Postal code",
  "region": "Region",
  "v8n_required": "Required",
  "v8n_too_long": "Too long",
  "spinner": {
    "loading_busy": "Loading",
    "loading_error": "Failed to load"
  }
}
