=== Foxy/foxy-elements/src/static/schemas/address-card.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "additionalProperties": false,
  "properties": {
    "default_billing_address": { "type": "string", "default": "Default billing address" },
    "default_shipping_address": { "type": "string", "default": "Default shipping address" },
    "full_address": {
      "type": "string",
      "default": "{{address1}} {{address2}} {{city}} {{region}} {{postal_code}}"
    },
    "full_name": { "type": "string", "default": "{{first_name}} {{last_name}}" },
    "spinner": {
      "additionalProperties": false,
      "properties": {
        "loading_busy": { "type": "string", "default": "Loading" },
        "loading_empty": { "type": "string", "default": "No data" },
        "loading_error": { "type": "string", "default": "Unknown error" }
      },
      "required": ["loading_busy", "loading_empty", "loading_error"]
    }
  },
  "required": [
    "default_billing_address",
    "default_shipping_address",
    "full_address",
    "full_name",
    "spinner"
  ]
}

=== Foxy/foxy-elements/src/static/translations/address-card/en.json
{
  "default_billing_address": "Default billing address",
  "default_shipping_address": "Default shipping address",
  "full_address": "{{address1}} {{address2}} {{city}} {{region}} {{postal_code}}",
  "full_name": "{{first_name}} {{last_name}}",
  "spinner": {
    "loading_busy": "Loading",
    "loading_empty": "No data",
    "loading_error": "Failed to load"
  }
}
