=== Foxy/foxy-elements/src/static/schemas/cancellation-form.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "properties": {
    "end_date": {
      "default": "End date",
      "type": "string"
    },
    "end_subscription": {
      "default": "End subscription",
      "type": "string"
    },
    "end_subscription_explainer": {
      "default": "Your subscription will remain active until the selected end date. You might have to resubscribe if you decide to resume this subscription later.",
      "type": "string"
    },
    "spinner": {
      "properties": {
        "loading_busy": {
          "$ref": "spinner.json#/properties/loading_busy"
        },
        "loading_error": {
          "$ref": "spinner.json#/properties/loading_error"
        }
      },
      "required": ["loading_busy", "loading_error"],
      "additionalProperties": false
    },
    "v8n_required": {
      "default": "Required",
      "type": "string"
    }
  },
  "required": [
    "end_date",
    "end_subscription",
    "end_subscription_explainer",
    "v8n_required",
    "spinner"
  ],
  "additionalProperties": false
}

=== Foxy/foxy-elements/src/static/translations/cancellation-form/en.json
{
  "end_date": "End date",
  "end_subscription": "End subscription",
  "end_subscription_explainer": "Your subscription will remain active until the selected end date. You might have to resubscribe if you decide to resume this subscription later.",
  "v8n_required": "Required",
  "spinner": {
    "loading_busy": "Loading",
    "loading_error": "Failed to load"
  }
}
