=== Foxy/foxy-elements/src/static/schemas/cart-card.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "properties": {
    "line_1": {
      "type": "string",
      "default": "{{ count }} item • {{ amount, price }}"
    },
    "line_1_plural": {
      "type": "string",
      "default": "{{ count }} items • {{ amount, price }}"
    },
    "line_1_approximate": {
      "type": "string",
      "default": "At least 20 items • {{ amount, price }}"
    },
    "line_2_one": {
      "type": "string",
      "default": "{{ name }}"
    },
    "line_2_many": {
      "type": "string",
      "default": "{{ name }} + more"
    },
    "line_2_empty": {
      "type": "string",
      "default": "Empty cart"
    },
    "no_customer": {
      "type": "string",
      "default": "Customer unknown"
    },
    "status": {
      "type": "string",
      "default": "{{ dateCreated, date }}"
    },
    "spinner": {
      "properties": {
        "loading_busy": {
          "$ref": "spinner.json#/properties/loading_busy"
        },
        "loading_empty": {
          "$ref": "spinner.json#/properties/loading_empty"
        },
        "loading_error": {
          "$ref": "spinner.json#/properties/loading_error"
        }
      },
      "required": ["loading_busy", "loading_empty", "loading_error"],
      "additionalProperties": false
    }
  },
  "required": [
    "line_1",
    "line_1_plural",
    "line_1_approximate",
    "line_2_one",
    "line_2_many",
    "line_2_empty",
    "no_customer",
    "spinner"
  ],
  "additionalProperties": false
}

=== Foxy/foxy-elements/src/static/translations/cart-card/en.json
{
  "line_1": "{{ count }} item • {{ amount, price }}",
  "line_1_plural": "{{ count }} items • {{ amount, price }}",
  "line_1_approximate": "At least 20 items • {{ amount, price }}",
  "line_2_one": "{{ name }}",
  "line_2_many": "{{ name }} + more",
  "line_2_empty": "Empty cart",
  "no_customer": "Customer unknown",
  "status": "{{ dateCreated, date }}",
  "spinner": {
    "loading_busy": "Loading",
    "loading_empty": "No data",
    "loading_error": "Failed to load"
  }
}
