=== Foxy/foxy-elements/src/static/schemas/country.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "additionalProperties": false,
  "properties": {
    "AF": { "type": "string", "default": "Afghanistan" },
    "AX": { "type": "string", "default": "Åland Islands" },
    "AL": { "type": "string", "default": "Albania" },
    "DZ": { "type": "string", "default": "Algeria" },
    "AS": { "type": "string", "default": "American Samoa" },
    "AD": { "type": "string", "default": "Andorra" },
    "AO": { "type": "string", "default": "Angola" },
    "AI": { "type": "string", "default": "Anguilla" },
    "AQ": { "type": "string", "default": "Antarctica" },
    "AG": { "type": "string", "default": "Antigua and Barbuda" },
    "AR": { "type": "string", "default": "Argentina" },
    "AM": { "type": "string", "default": "Armenia" },
    "AW": { "type": "string", "default": "Aruba" },
    "AU": { "type": "string", "default": "Australia" },
    "AT": { "type": "string", "default": "Austria" },
    "AZ": { "type": "string", "default": "Azerbaijan" },
    "BS": { "type": "string", "default": "Bahamas" },
    "BH": { "type": "string", "default": "Bahrain" },
    "BD": { "type": "string", "default": "Bangladesh" },
    "BB": { "type": "string", "default": "Barbados" },
    "BY": { "type": "string", "default": "Belarus" },
    "BE": { "type": "string", "default": "Belgium" },
    "BZ": { "type": "string", "default": "Belize" },
    "BJ": { "type": "string", "default": "Benin" },
    "BM": { "type": "string", "default": "Bermuda" },
    "BT": { "type": "string", "default": "Bhutan" },
    "BO": { "type": "string", "default": "Bolivia" },
    "BQ": { "type": "string", "default": "Bonaire, Sint Eustatius and Saba" },
    "BA": { "type": "string", "default": "Bosnia and Herzegovina" },
    "BW": { "type": "string", "default": "Botswana" },
    "BV": { "type": "string", "default": "Bouvet Island" },
    "BR": { "type": "string", "default": "Brazil" },
    "IO": { "type": "string", "default": "British Indian Ocean Territory" },
    "BN": { "type": "string", "default": "Brunei Darussalam" },
    "BG": { "type": "string", "default": "Bulgaria" },
    "BF": { "type": "string", "default": "Burkina Faso" },
    "BI": { "type": "string", "default": "Burundi" },
    "KH": { "type": "string", "default": "Cambodia" },
    "CM": { "type": "string", "default": "Cameroon" },
    "CA": { "type": "string", "default": "Canada" },
    "CV": { "type": "string", "default": "Cape Verde" },
    "CW": { "type": "string", "default": "Curaçao" },
    "KY": { "type": "string", "default": "Cayman Islands" },
    "CF": { "type": "string", "default": "Central African Republic" },
    "TD": { "type": "string", "default": "Chad" },
    "CL": { "type": "string", "default": "Chile" },
    "CN": { "type": "string", "default": "China" },
    "CX": { "type": "string", "default": "Christmas Island" },
    "CC": { "type": "string", "default": "Cocos (Keeling) Islands" },
    "CO": { "type": "string", "default": "Colombia" },
    "KM": { "type": "string", "default": "Comoros" },
    "CG": { "type": "string", "default": "Congo" },
    "CD": { "type": "string", "default": "Congo, the Democratic Republic of the" },
    "CK": { "type": "string", "default": "Cook Islands" },
    "CR": { "type": "string", "default": "Costa Rica" },
    "CI": { "type": "string", "default": "Cote DIvoire" },
    "HR": { "type": "string", "default": "Croatia" },
    "CU": { "type": "string", "default": "Cuba" },
    "CY": { "type": "string", "default": "Cyprus" },
    "CZ": { "type": "string", "default": "Czech Republic" },
    "DK": { "type": "string", "default": "Denmark" },
    "DJ": { "type": "string", "default": "Djibouti" },
    "DM": { "type": "string", "default": "Dominica" },
    "DO": { "type": "string", "default": "Dominican Republic" },
    "EC": { "type": "string", "default": "Ecuador" },
    "EG": { "type": "string", "default": "Egypt" },
    "SV": { "type": "string", "default": "El Salvador" },
    "SX": { "type": "string", "default": "Sint Maarten" },
    "GQ": { "type": "string", "default": "Equatorial Guinea" },
    "ER": { "type": "string", "default": "Eritrea" },
    "EE": { "type": "string", "default": "Estonia" },
    "ET": { "type": "string", "default": "Ethiopia" },
    "FK": { "type": "string", "default": "Falkland Islands (Malvinas)" },
    "FO": { "type": "string", "default": "Faroe Islands" },
    "FJ": { "type": "string", "default": "Fiji" },
    "FI": { "type": "string", "default": "Finland" },
    "FR": { "type": "string", "default": "France" },
    "GF": { "type": "string", "default": "French Guiana" },
    "PF": { "type": "string", "default": "French Polynesia" },
    "TF": { "type": "string", "default": "French Southern Territories" },
    "GA": { "type": "string", "default": "Gabon" },
    "GM": { "type": "string", "default": "Gambia" },
    "GE": { "type": "string", "default": "Georgia" },
    "DE": { "type": "string", "default": "Germany" },
    "GH": { "type": "string", "default": "Ghana" },
    "GI": { "type": "string", "default": "Gibraltar" },
    "GR": { "type": "string", "default": "Greece" },
    "GL": { "type": "string", "default": "Greenland" },
    "GD": { "type": "string", "default": "Grenada" },
    "GP": { "type": "string", "default": "Guadeloupe" },
    "GU": { "type": "string", "default": "Guam" },
    "GT": { "type": "string", "default": "Guatemala" },
    "GG": { "type": "string", "default": "Guernsey" },
    "GN": { "type": "string", "default": "Guinea" },
    "GW": { "type": "string", "default": "Guinea-bissau" },
    "GY": { "type": "string", "default": "Guyana" },
    "HT": { "type": "string", "default": "Haiti" },
    "HM": { "type": "string", "default": "Heard Island and McDonald Island" },
    "VA": { "type": "string", "default": "Holy See (Vatican City State)" },
    "HN": { "type": "string", "default": "Honduras" },
    "HK": { "type": "string", "default": "Hong Kong" },
    "HU": { "type": "string", "default": "Hungary" },
    "IS": { "type": "string", "default": "Iceland" },
    "IN": { "type": "string", "default": "India" },
    "ID": { "type": "string", "default": "Indonesia" },
    "IR": { "type": "string", "default": "Iran, Islamic Republic of" },
    "IQ": { "type": "string", "default": "Iraq" },
    "IE": { "type": "string", "default": "Ireland" },
    "IM": { "type": "string", "default": "Isle of Man" },
    "IL": { "type": "string", "default": "Israel" },
    "IT": { "type": "string", "default": "Italy" },
    "JM": { "type": "string", "default": "Jamaica" },
    "JP": { "type": "string", "default": "Japan" },
    "JE": { "type": "string", "default": "Jersey" },
    "JO": { "type": "string", "default": "Jordan" },
    "KZ": { "type": "string", "default": "Kazakhstan" },
    "KE": { "type": "string", "default": "Kenya" },
    "KI": { "type": "string", "default": "Kiribati" },
    "KP": { "type": "string", "default": "Korea, Democratic People's Republic of" },
    "KR": { "type": "string", "default": "Korea, Republic of" },
    "KW": { "type": "string", "default": "Kuwait" },
    "KG": { "type": "string", "default": "Kyrgyzstan" },
    "LA": { "type": "string", "default": "Lao People's Democratic Republic" },
    "LV": { "type": "string", "default": "Latvia" },
    "LB": { "type": "string", "default": "Lebanon" },
    "LS": { "type": "string", "default": "Lesotho" },
    "LR": { "type": "string", "default": "Liberia" },
    "LY": { "type": "string", "default": "Libya" },
    "LI": { "type": "string", "default": "Liechtenstein" },
    "LT": { "type": "string", "default": "Lithuania" },
    "LU": { "type": "string", "default": "Luxembourg" },
    "MO": { "type": "string", "default": "Macau Special Administrative Region of China" },
    "MK": { "type": "string", "default": "North Macedonia" },
    "MG": { "type": "string", "default": "Madagascar" },
    "MW": { "type": "string", "default": "Malawi" },
    "MY": { "type": "string", "default": "Malaysia" },
    "MV": { "type": "string", "default": "Maldives" },
    "ML": { "type": "string", "default": "Mali" },
    "MT": { "type": "string", "default": "Malta" },
    "MH": { "type": "string", "default": "Marshall Islands" },
    "MQ": { "type": "string", "default": "Martinique" },
    "MR": { "type": "string", "default": "Mauritania" },
    "MU": { "type": "string", "default": "Mauritius" },
    "YT": { "type": "string", "default": "Mayotte" },
    "MX": { "type": "string", "default": "Mexico" },
    "FM": { "type": "string", "default": "Micronesia, Federated States of" },
    "MD": { "type": "string", "default": "Moldova, Republic of" },
    "MC": { "type": "string", "default": "Monaco" },
    "MN": { "type": "string", "default": "Mongolia" },
    "ME": { "type": "string", "default": "Montenegro" },
    "MS": { "type": "string", "default": "Montserrat" },
    "MA": { "type": "string", "default": "Morocco" },
    "MZ": { "type": "string", "default": "Mozambique" },
    "MM": { "type": "string", "default": "Myanmar" },
    "NA": { "type": "string", "default": "Namibia" },
    "NR": { "type": "string", "default": "Nauru" },
    "NP": { "type": "string", "default": "Nepal" },
    "NL": { "type": "string", "default": "Netherlands" },
    "NC": { "type": "string", "default": "New Caledonia" },
    "NZ": { "type": "string", "default": "New Zealand" },
    "NI": { "type": "string", "default": "Nicaragua" },
    "NE": { "type": "string", "default": "Niger" },
    "NG": { "type": "string", "default": "Nigeria" },
    "NU": { "type": "string", "default": "Niue" },
    "NF": { "type": "string", "default": "Norfolk Island" },
    "MP": { "type": "string", "default": "Northern Mariana Islands" },
    "NO": { "type": "string", "default": "Norway" },
    "OM": { "type": "string", "default": "Oman" },
    "PK": { "type": "string", "default": "Pakistan" },
    "PW": { "type": "string", "default": "Palau" },
    "PS": { "type": "string", "default": "Palestine, State of" },
    "PA": { "type": "string", "default": "Panama" },
    "PG": { "type": "string", "default": "Papua New Guinea" },
    "PY": { "type": "string", "default": "Paraguay" },
    "PE": { "type": "string", "default": "Peru" },
    "PH": { "type": "string", "default": "Philippines" },
    "PN": { "type": "string", "default": "Pitcairn" },
    "PL": { "type": "string", "default": "Poland" },
    "PT": { "type": "string", "default": "Portugal" },
    "PR": { "type": "string", "default": "Puerto Rico" },
    "QA": { "type": "string", "default": "Qatar" },
    "RE": { "type": "string", "default": "Réunion" },
    "RO": { "type": "string", "default": "Romania" },
    "RU": { "type": "string", "default": "Russian Federation" },
    "RW": { "type": "string", "default": "Rwanda" },
    "BL": { "type": "string", "default": "Saint Barthélemy" },
    "SH": { "type": "string", "default": "Saint Helena, Ascension and Tristan da Cunha" },
    "KN": { "type": "string", "default": "Saint Kitts and Nevis" },
    "LC": { "type": "string", "default": "Saint Lucia" },
    "MF": { "type": "string", "default": "Saint Martin" },
    "PM": { "type": "string", "default": "Saint Pierre and Miquelon" },
    "VC": { "type": "string", "default": "Saint Vincent and the Grenadines" },
    "WS": { "type": "string", "default": "Samoa" },
    "SM": { "type": "string", "default": "San Marino" },
    "SS": { "type": "string", "default": "South Sudan" },
    "ST": { "type": "string", "default": "Sao Tome and Principe" },
    "SA": { "type": "string", "default": "Saudi Arabia" },
    "SN": { "type": "string", "default": "Senegal" },
    "RS": { "type": "string", "default": "Serbia" },
    "SC": { "type": "string", "default": "Seychelles" },
    "SL": { "type": "string", "default": "Sierra Leone" },
    "SG": { "type": "string", "default": "Singapore" },
    "SK": { "type": "string", "default": "Slovakia" },
    "SI": { "type": "string", "default": "Slovenia" },
    "SB": { "type": "string", "default": "Solomon Islands" },
    "SO": { "type": "string", "default": "Somalia" },
    "ZA": { "type": "string", "default": "South Africa" },
    "GS": { "type": "string", "default": "South Georgia and the South Sandwich Islands" },
    "ES": { "type": "string", "default": "Spain" },
    "LK": { "type": "string", "default": "Sri Lanka" },
    "SD": { "type": "string", "default": "Sudan" },
    "SR": { "type": "string", "default": "Suriname" },
    "SJ": { "type": "string", "default": "Svalbard and Jan Mayen" },
    "SZ": { "type": "string", "default": "Eswatini" },
    "SE": { "type": "string", "default": "Sweden" },
    "CH": { "type": "string", "default": "Switzerland" },
    "SY": { "type": "string", "default": "Syrian Arab Republic" },
    "TW": { "type": "string", "default": "Taiwan" },
    "TJ": { "type": "string", "default": "Tajikistan" },
    "TZ": { "type": "string", "default": "Tanzania, United Republic of" },
    "TH": { "type": "string", "default": "Thailand" },
    "TL": { "type": "string", "default": "Timor-Leste" },
    "TG": { "type": "string", "default": "Togo" },
    "TK": { "type": "string", "default": "Tokelau" },
    "TO": { "type": "string", "default": "Tonga" },
    "TT": { "type": "string", "default": "Trinidad and Tobago" },
    "TN": { "type": "string", "default": "Tunisia" },
    "TR": { "type": "string", "default": "Turkey" },
    "TM": { "type": "string", "default": "Turkmenistan" },
    "TC": { "type": "string", "default": "Turks and Caicos Islands" },
    "TV": { "type": "string", "default": "Tuvalu" },
    "UG": { "type": "string", "default": "Uganda" },
    "UA": { "type": "string", "default": "Ukraine" },
    "AE": { "type": "string", "default": "United Arab Emirates" },
    "GB": { "type": "string", "default": "United Kingdom" },
    "US": { "type": "string", "default": "United States" },
    "UM": { "type": "string", "default": "United States Minor Outlying Islands" },
    "UY": { "type": "string", "default": "Uruguay" },
    "UZ": { "type": "string", "default": "Uzbekistan" },
    "VU": { "type": "string", "default": "Vanuatu" },
    "VE": { "type": "string", "default": "Venezuela" },
    "VN": { "type": "string", "default": "Vietnam" },
    "VG": { "type": "string", "default": "Virgin Islands, British" },
    "VI": { "type": "string", "default": "Virgin Islands, U.S." },
    "WF": { "type": "string", "default": "Wallis and Futuna Islands" },
    "EH": { "type": "string", "default": "Western Sahara" },
    "YE": { "type": "string", "default": "Yemen" },
    "ZM": { "type": "string", "default": "Zambia" },
    "ZW": { "type": "string", "default": "Zimbabwe" }
  },
  "required": [
    "AF",
    "AX",
    "AL",
    "DZ",
    "AS",
    "AD",
    "AO",
    "AI",
    "AQ",
    "AG",
    "AR",
    "AM",
    "AW",
    "AU",
    "AT",
    "AZ",
    "BS",
    "BH",
    "BD",
    "BB",
    "BY",
    "BE",
    "BZ",
    "BJ",
    "BM",
    "BT",
    "BO",
    "BQ",
    "BA",
    "BW",
    "BV",
    "BR",
    "IO",
    "BN",
    "BG",
    "BF",
    "BI",
    "KH",
    "CM",
    "CA",
    "CV",
    "CW",
    "KY",
    "CF",
    "TD",
    "CL",
    "CN",
    "CX",
    "CC",
    "CO",
    "KM",
    "CG",
    "CD",
    "CK",
    "CR",
    "CI",
    "HR",
    "CU",
    "CY",
    "CZ",
    "DK",
    "DJ",
    "DM",
    "DO",
    "EC",
    "EG",
    "SV",
    "SX",
    "GQ",
    "ER",
    "EE",
    "ET",
    "FK",
    "FO",
    "FJ",
    "FI",
    "FR",
    "GF",
    "PF",
    "TF",
    "GA",
    "GM",
    "GE",
    "DE",
    "GH",
    "GI",
    "GR",
    "GL",
    "GD",
    "GP",
    "GU",
    "GT",
    "GG",
    "GN",
    "GW",
    "GY",
    "HT",
    "HM",
    "VA",
    "HN",
    "HK",
    "HU",
    "IS",
    "IN",
    "ID",
    "IR",
    "IQ",
    "IE",
    "IM",
    "IL",
    "IT",
    "JM",
    "JP",
    "JE",
    "JO",
    "KZ",
    "KE",
    "KI",
    "KP",
    "KR",
    "KW",
    "KG",
    "LA",
    "LV",
    "LB",
    "LS",
    "LR",
    "LY",
    "LI",
    "LT",
    "LU",
    "MO",
    "MK",
    "MG",
    "MW",
    "MY",
    "MV",
    "ML",
    "MT",
    "MH",
    "MQ",
    "MR",
    "MU",
    "YT",
    "MX",
    "FM",
    "MD",
    "MC",
    "MN",
    "ME",
    "MS",
    "MA",
    "MZ",
    "MM",
    "NA",
    "NR",
    "NP",
    "NL",
    "NC",
    "NZ",
    "NI",
    "NE",
    "NG",
    "NU",
    "NF",
    "MP",
    "NO",
    "OM",
    "PK",
    "PW",
    "PS",
    "PA",
    "PG",
    "PY",
    "PE",
    "PH",
    "PN",
    "PL",
    "PT",
    "PR",
    "QA",
    "RE",
    "RO",
    "RU",
    "RW",
    "BL",
    "SH",
    "KN",
    "LC",
    "MF",
    "PM",
    "VC",
    "WS",
    "SM",
    "SS",
    "ST",
    "SA",
    "SN",
    "RS",
    "SC",
    "SL",
    "SG",
    "SK",
    "SI",
    "SB",
    "SO",
    "ZA",
    "GS",
    "ES",
    "LK",
    "SD",
    "SR",
    "SJ",
    "SZ",
    "SE",
    "CH",
    "SY",
    "TW",
    "TJ",
    "TZ",
    "TH",
    "TL",
    "TG",
    "TK",
    "TO",
    "TT",
    "TN",
    "TR",
    "TM",
    "TC",
    "TV",
    "UG",
    "UA",
    "AE",
    "GB",
    "US",
    "UM",
    "UY",
    "UZ",
    "VU",
    "VE",
    "VN",
    "VG",
    "VI",
    "WF",
    "EH",
    "YE",
    "ZM",
    "ZW"
  ]
}

=== Foxy/foxy-elements/src/static/translations/country/pl.json
{
  "AF": "Afganistan",
  "AX": "Wyspy Alandzkie",
  "AL": "Albania",
  "DZ": "Algeria",
  "AS": "Samoa Amerykańskie",
  "AD": "Andora",
  "AO": "Angola",
  "AI": "Anguilla",
  "AQ": "Antarktyda",
  "AG": "Antigua i Barbuda",
  "AR": "Argentyna",
  "AM": "Armenia",
  "AW": "Aruba",
  "AU": "Australia",
  "AT": "Austria",
  "AZ": "Azerbeidżan",
  "BS": "Bahamy",
  "BH": "Bahrain",
  "BD": "Bangladesz",
  "BB": "Barbados",
  "BY": "Białoruś",
  "BE": "Belgia",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermudy",
  "BT": "Bhutan",
  "BO": "Boliwia",
  "BQ": "Bonaire, Sint Eustatius i Saba",
  "BA": "Bośnia i Hercegowina",
  "BW": "Botswana",
  "BV": "Wyspa Bouveta",
  "BR": "Brazylia",
  "IO": "Brytyjskie Terytorium Oceanu Indyjskiego",
  "BN": "Brunei Darussalam",
  "BG": "Bułgaria",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "KH": "Kambodża",
  "CM": "Kamerun",
  "CA": "Kanada",
  "CV": "Wyspy Zielonego Przylądka",
  "CW": "Curaçao",
  "KY": "Kajmany",
  "CF": "Republika Środkowoafrykańska",
  "TD": "Czad",
  "CL": "Czile",
  "CN": "Chiny",
  "CX": "Wyspa Bożego Narodzenia",
  "CC": "Wyspy Kokosowe (Keelinga)",
  "CO": "Kolumbia",
  "KM": "Komory",
  "CG": "Kongo",
  "CD": "Kongo, Demokratyczna Republika",
  "CK": "Wyspy Cooka",
  "CR": "Kostaryka",
  "CI": "Cote Divoire",
  "HR": "Chorwacja",
  "CU": "Kuba",
  "CY": "Cypr",
  "CZ": "Czechy",
  "DK": "Dania",
  "DJ": "Dżibuti",
  "DM": "Dominika",
  "DO": "Dominikana",
  "EC": "Ekwador",
  "EG": "Egipt",
  "SV": "Salwador",
  "SX": "Sint Maarten",
  "GQ": "Gwinea Równikowa",
  "ER": "Erytrea",
  "EE": "Estonia",
  "ET": "Etiopia",
  "FK": "Falklandy (Malwiny)",
  "FO": "Wyspy Owcze",
  "FJ": "Fidżi",
  "FI": "Finlandia",
  "FR": "Francja",
  "GF": "Gujana Francuska",
  "PF": "Polinezja Francuska",
  "TF": "Francuskie Terytoria Południowe",
  "GA": "Gabon",
  "GM": "Gambia",
  "GE": "Gruzja",
  "DE": "Niemcy",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GR": "Grecja",
  "GL": "Grenlandia",
  "GD": "Grenada",
  "GP": "Gwadelupa",
  "GU": "Guam",
  "GT": "Gwatemala",
  "GG": "Guernsey",
  "GN": "Gwinea",
  "GW": "Gwinea Bissau",
  "GY": "Gujana",
  "HT": "Haiti",
  "HM": "Wyspy Heard i McDonalda",
  "VA": "Stolica Apostolska (Państwo Watykańskie)",
  "HN": "Honduras",
  "HK": "Hong Kong",
  "HU": "Węgry",
  "IS": "Islandia",
  "IN": "Indie",
  "ID": "Indonezja",
  "IR": "Iran",
  "IQ": "Irak",
  "IE": "Irlandia",
  "IM": "Wyspa Man",
  "IL": "Izrael",
  "IT": "Włochy",
  "JM": "Jamajka",
  "JP": "Japonia",
  "JE": "Jersey",
  "JO": "Jordania",
  "KZ": "Kazachstan",
  "KE": "Kenia",
  "KI": "Kiribati",
  "KP": "Korea, Republika Ludowo-Demokratyczna",
  "KR": "Republika Korei",
  "KW": "Kuwejt",
  "KG": "Kirgistan",
  "LA": "Laotańska Republika Ludowo-Demokratyczna",
  "LV": "Łotwa",
  "LB": "Liban",
  "LS": "Lesoto",
  "LR": "Liberia",
  "LY": "Libia",
  "LI": "Liechtenstein",
  "LT": "Litwa",
  "LU": "Luksemburg",
  "MO": "Specjalny Region Administracyjny Makau w Chinach",
  "MK": "Macedonia Północna",
  "MG": "Madagaskar",
  "MW": "Malawi",
  "MY": "Malezja",
  "MV": "Malediwy",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Wyspy Marshalla",
  "MQ": "Martynika",
  "MR": "Mauretania",
  "MU": "Mauritius",
  "YT": "Majotta",
  "MX": "Meksyk",
  "FM": "Mikronezja, Sfederowane Stany",
  "MD": "Mołdawia, Republika",
  "MC": "Monako",
  "MN": "Mongolia",
  "ME": "Czarnogóra",
  "MS": "Montserrat",
  "MA": "Maroko",
  "MZ": "Mozambik",
  "MM": "Myanmar",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Niderlandy",
  "NC": "Nowa Kaledonia",
  "NZ": "Nowa Zelandia",
  "NI": "Nikaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "NU": "Niue",
  "NF": "Wyspa Norfolk",
  "MP": "Mariany Północne",
  "NO": "Norwegia",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PS": "Palestyna",
  "PA": "Panama",
  "PG": "Papua Nowa Gwinea",
  "PY": "Paragwaj",
  "PE": "Peru",
  "PH": "Filipiny",
  "PN": "Pitcairn",
  "PL": "Polska",
  "PT": "Portugalia",
  "PR": "Portoryko",
  "QA": "Katar",
  "RE": "Réunion",
  "RO": "Rumunia",
  "RU": "Federacja Rosyjska",
  "RW": "Rwanda",
  "BL": "Saint Barthelemy",
  "SH": "Saint Helena i Tristan da Cunha",
  "KN": "Saint Kitts i Nevis",
  "LC": "Saint Lucia",
  "MF": "Saint Martin",
  "PM": "Saint Pierre i Miquelon",
  "VC": "Saint Vincent i Grenadyny",
  "WS": "Samoa",
  "SM": "San Marino",
  "SS": "Południowy Sudan",
  "ST": "Wyspy Świętego Tomasza i Książęca",
  "SA": "Arabia Saudyjska",
  "SN": "Senegal",
  "RS": "Serbia",
  "SC": "Seszele",
  "SL": "Sierra Leone",
  "SG": "Singapur",
  "SK": "Słowacja",
  "SI": "Słowenia",
  "SB": "Wyspy Salomona",
  "SO": "Somalia",
  "ZA": "Afryka Południowa",
  "GS": "Georgia Południowa i Sandwich Południowy",
  "ES": "Hiszpania",
  "LK": "Sri Lanka",
  "SD": "Sudan",
  "SR": "Surinam",
  "SJ": "Svalbard i Jan Mayen",
  "SZ": "Eswatini",
  "SE": "Szwecja",
  "CH": "Szwajcaria",
  "SY": "Republika Syryjsko-Arabska",
  "TW": "Tajwan",
  "TJ": "Tadżykistan",
  "TZ": "Tanzania, Zjednoczona Republika",
  "TH": "Tajlandia",
  "TL": "Timor Wschodni",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinidad i Tobago",
  "TN": "Tunezja",
  "TR": "Turcja",
  "TM": "Turkmenia",
  "TC": "Wyspy Turks i Caicos",
  "TV": "Tuvalu",
  "UG": "Uganda",
  "UA": "Ukraina",
  "AE": "Zjednoczone Emiraty Arabskie",
  "GB": "Wielka Brytania",
  "US": "Stany Zjednoczone",
  "UM": "Stany Zjednoczone Dalekie Wyspy Mniejsze",
  "UY": "Urugwaj",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VE": "Wenezuela",
  "VN": "Wietnam",
  "VG": "Wyspy Dziewicze, Brytyjskie",
  "VI": "Wyspy Dziewicze Stanów Zjednoczonych",
  "WF": "Wyspy Wallis i Futuna",
  "EH": "Sahara Zachodnia",
  "YE": "Jemen",
  "ZM": "Zambia",
  "ZW": "Zimbabwe"
}
