=== Foxy/foxy-elements/src/static/schemas/coupon-code-card.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "additionalProperties": false,
  "properties": {
    "line_1": { "type": "string", "default": "{{ code }}" },
    "line_2": {
      "type": "string",
      "default": "Added on {{ date_created, date }} at {{ date_created, time }}"
    },
    "uses_count": { "type": "string", "default": "Used {{ count }} time" },
    "uses_count_plural": { "type": "string", "default": "Used {{ count }} times" },
    "spinner": {
      "additionalProperties": false,
      "properties": {
        "loading_busy": { "type": "string", "default": "Loading" },
        "loading_empty": { "type": "string", "default": "No data" },
        "loading_error": { "type": "string", "default": "Unknown error" }
      },
      "required": ["loading_busy", "loading_empty", "loading_error"]
    }
  },
  "required": ["line_1", "line_2", "uses_count", "uses_count_plural", "spinner"]
}

=== Foxy/foxy-elements/src/static/translations/coupon-code-card/en.json
{
  "line_1": "{{ code }}",
  "line_2": "Added on {{ date_created, date }} at {{ date_created, time }}",
  "uses_count": "Used {{ count }} time",
  "uses_count_plural": "Used {{ count }} times",
  "spinner": {
    "loading_busy": "Loading",
    "loading_empty": "No data",
    "loading_error": "Unknown error"
  }
}
