=== Foxy/foxy-elements/src/static/schemas/coupon-code-form.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "properties": {
    "cancel": {
      "default": "Cancel",
      "type": "string"
    },
    "code": {
      "default": "Code",
      "type": "string"
    },
    "confirm": {
      "default": "Confirm",
      "type": "string"
    },
    "create": {
      "default": "Create",
      "type": "string"
    },
    "date": {
      "default": "{{value, date}}",
      "type": "string"
    },
    "date_created": {
      "default": "Created on",
      "type": "string"
    },
    "date_modified": {
      "default": "Last updated",
      "type": "string"
    },
    "delete": {
      "default": "Delete",
      "type": "string"
    },
    "delete_prompt": {
      "default": "This resource will be permanently removed. Are you sure?",
      "type": "string"
    },
    "spinner": {
      "properties": {
        "loading_busy": {
          "$ref": "spinner.json#/properties/loading_busy"
        },
        "loading_error": {
          "$ref": "spinner.json#/properties/loading_error"
        }
      },
      "required": ["loading_busy", "loading_error"],
      "additionalProperties": false
    },
    "v8n_required": {
      "default": "Required",
      "type": "string"
    },
    "v8n_too_long": {
      "default": "Too long",
      "type": "string"
    }
  },
  "required": [
    "cancel",
    "code",
    "confirm",
    "create",
    "date",
    "date_created",
    "date_modified",
    "delete",
    "delete_prompt",
    "v8n_required",
    "v8n_too_long",
    "spinner"
  ],
  "additionalProperties": false
}

=== Foxy/foxy-elements/src/static/translations/coupon-code-form/en.json
{
  "cancel": "Cancel",
  "code": "Code",
  "confirm": "Confirm",
  "create": "Create",
  "date": "{{value, date}}",
  "date_created": "Created on",
  "date_modified": "Last updated",
  "delete": "Delete",
  "delete_prompt": "This resource will be permanently removed. Are you sure?",
  "v8n_required": "Required",
  "v8n_too_long": "Too long",
  "spinner": {
    "loading_busy": "Loading",
    "loading_error": "Failed to load"
  }
}
