=== Foxy/foxy-elements/src/static/schemas/coupon-card.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "properties": {
    "allunits_price_amount_discount_summary": {
      "default": "{{adjustment}}¤ each after {{from}}",
      "type": "string"
    },
    "allunits_price_percentage_discount_summary": {
      "default": "{{adjustment, percent}} after {{from}}",
      "type": "string"
    },
    "allunits_quantity_amount_discount_summary": {
      "default": "{{adjustment}}¤ each on orders of {{from}}+",
      "type": "string"
    },
    "allunits_quantity_percentage_discount_summary": {
      "default": "{{adjustment, percent}} on orders of {{from}}+",
      "type": "string"
    },
    "date_range_any": {
      "default": "Ongoing",
      "type": "string"
    },
    "date_range_complete": {
      "default": "{{start, date}} – {{end, date}}",
      "type": "string"
    },
    "date_range_from": {
      "default": "From {{start, date}}",
      "type": "string"
    },
    "date_range_until": {
      "default": "Until {{end, date}}",
      "type": "string"
    },
    "discount_summary": {
      "default": "{{params, discount}}",
      "type": "string"
    },
    "incremental_price_amount_discount_summary": {
      "default": "{{adjustment}}¤ each on orders of {{from}}+",
      "type": "string"
    },
    "incremental_price_percentage_discount_summary": {
      "default": "{{adjustment, percent}} on orders of {{from}}+",
      "type": "string"
    },
    "incremental_quantity_amount_discount_summary": {
      "default": "{{adjustment}}¤ each on items {{from}}+",
      "type": "string"
    },
    "incremental_quantity_percentage_discount_summary": {
      "default": "{{adjustment, percent}} on items {{from}}+",
      "type": "string"
    },
    "ordinal_few": {
      "default": "rd",
      "type": "string"
    },
    "ordinal_many": {
      "default": "th",
      "type": "string"
    },
    "ordinal_one": {
      "default": "st",
      "type": "string"
    },
    "ordinal_other": {
      "default": "th",
      "type": "string"
    },
    "ordinal_two": {
      "default": "nd",
      "type": "string"
    },
    "ordinal_zero": {
      "default": "th",
      "type": "string"
    },
    "repeat_price_amount_discount_summary": {
      "default": "for each {{from}}, {{adjustment}}¤ on the next item",
      "type": "string"
    },
    "repeat_price_percentage_discount_summary": {
      "default": "for each {{from}}, {{adjustment, percent}} on the next item",
      "type": "string"
    },
    "repeat_quantity_amount_discount_summary": {
      "default": "{{adjustment}}¤ on each {{from, ordinal}} item",
      "type": "string"
    },
    "repeat_quantity_percentage_discount_summary": {
      "default": "{{adjustment, percent}} on each {{from, ordinal}} item",
      "type": "string"
    },
    "single_price_amount_discount_summary": {
      "default": "{{adjustment}}¤ after {{from}}",
      "type": "string"
    },
    "single_price_percentage_discount_summary": {
      "default": "{{adjustment, percent}} after {{from}}",
      "type": "string"
    },
    "single_quantity_amount_discount_summary": {
      "default": "{{adjustment}}¤ after {{from}} items",
      "type": "string"
    },
    "single_quantity_percentage_discount_summary": {
      "default": "{{adjustment, percent}} after {{from}} items",
      "type": "string"
    },
    "spinner": {
      "properties": {
        "loading_busy": {
          "$ref": "spinner.json#/properties/loading_busy"
        },
        "loading_empty": {
          "$ref": "spinner.json#/properties/loading_empty"
        },
        "loading_error": {
          "$ref": "spinner.json#/properties/loading_error"
        }
      },
      "required": ["loading_busy", "loading_empty", "loading_error"],
      "additionalProperties": false
    },
    "uses_count": {
      "default": "{{count}} uses",
      "type": "string"
    },
    "uses_to_total_count": {
      "default": "{{count}}/{{total}} uses",
      "type": "string"
    }
  },
  "required": [
    "allunits_price_amount_discount_summary",
    "allunits_price_percentage_discount_summary",
    "allunits_quantity_amount_discount_summary",
    "allunits_quantity_percentage_discount_summary",
    "date_range_any",
    "date_range_complete",
    "date_range_from",
    "date_range_until",
    "discount_summary",
    "incremental_price_amount_discount_summary",
    "incremental_price_percentage_discount_summary",
    "incremental_quantity_amount_discount_summary",
    "incremental_quantity_percentage_discount_summary",
    "ordinal_few",
    "ordinal_many",
    "ordinal_one",
    "ordinal_other",
    "ordinal_two",
    "ordinal_zero",
    "repeat_price_amount_discount_summary",
    "repeat_price_percentage_discount_summary",
    "repeat_quantity_amount_discount_summary",
    "repeat_quantity_percentage_discount_summary",
    "single_price_amount_discount_summary",
    "single_price_percentage_discount_summary",
    "single_quantity_amount_discount_summary",
    "single_quantity_percentage_discount_summary",
    "uses_count",
    "uses_to_total_count",
    "spinner"
  ],
  "additionalProperties": false
}

=== Foxy/foxy-elements/src/static/translations/coupon-card/en.json
{
  "allunits_price_amount_discount_summary": "{{adjustment}}¤ amount each after {{from}}",
  "allunits_price_percentage_discount_summary": "{{adjustment, percent}} after {{from}}",
  "allunits_quantity_amount_discount_summary": "{{adjustment}}¤ amount each on orders of {{from}}+",
  "allunits_quantity_percentage_discount_summary": "{{adjustment, percent}} on orders of {{from}}+",
  "date_range_any": "Ongoing",
  "date_range_complete": "{{start, date}} – {{end, date}}",
  "date_range_from": "From {{start, date}}",
  "date_range_until": "Until {{end, date}}",
  "discount_summary": "{{params, discount}}",
  "incremental_price_amount_discount_summary": "{{adjustment}}¤ amount each on orders of {{from}}+",
  "incremental_price_percentage_discount_summary": "{{adjustment, percent}} on orders of {{from}}+",
  "incremental_quantity_amount_discount_summary": "{{adjustment}}¤ amount each on items {{from}}+",
  "incremental_quantity_percentage_discount_summary": "{{adjustment, percent}} on items {{from}}+",
  "ordinal_few": "rd",
  "ordinal_many": "th",
  "ordinal_one": "st",
  "ordinal_other": "th",
  "ordinal_two": "nd",
  "ordinal_zero": "th",
  "repeat_price_amount_discount_summary": "for each {{from}}, {{adjustment}}¤ amount on the next item",
  "repeat_price_percentage_discount_summary": "for each {{from}}, {{adjustment, percent}} on the next item",
  "repeat_quantity_amount_discount_summary": "{{adjustment}}¤ amount on each {{from, ordinal}} item",
  "repeat_quantity_percentage_discount_summary": "{{adjustment, percent}} on each {{from, ordinal}} item",
  "single_price_amount_discount_summary": "{{adjustment}}¤ amount after {{from}}",
  "single_price_percentage_discount_summary": "{{adjustment, percent}} after {{from}}",
  "single_quantity_amount_discount_summary": "{{adjustment}}¤ amount after {{from}} item(s)",
  "single_quantity_percentage_discount_summary": "{{adjustment, percent}} after {{from}} item(s)",
  "uses_count": "{{count}} uses",
  "uses_to_total_count": "{{count}}/{{total}} uses",
  "spinner": {
    "loading_busy": "Loading",
    "loading_empty": "No data",
    "loading_error": "Unknown error"
  }
}
