=== Foxy/foxy-elements/src/static/schemas/email-template-form.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "additionalProperties": false,
  "properties": {
    "cache": { "type": "string", "default": "Cache" },
    "cancel": { "type": "string", "default": "Cancel" },
    "confirm": { "type": "string", "default": "Confirm" },
    "create": { "type": "string", "default": "Create" },
    "date": { "type": "string", "default": "{{value, date}}" },
    "date_created": { "type": "string", "default": "Created on" },
    "date_modified": { "type": "string", "default": "Last updated" },
    "default": { "type": "string", "default": "Default" },
    "delete": { "type": "string", "default": "Delete" },
    "delete_prompt": {
      "type": "string",
      "default": "This resource will be permanently removed. Are you sure?"
    },
    "description": { "type": "string", "default": "Description" },
    "html_template": { "type": "string", "default": "HTML template" },
    "template_clipboard": { "type": "string", "default": "From clipboard" },
    "template_clipboard_explainer": {
      "type": "string",
      "default": "Paste the template here to use it"
    },
    "template_default": { "type": "string", "default": "Default" },
    "template_default_explainer": { "type": "string", "default": "Use the default template" },
    "template_url": { "type": "string", "default": "From URL" },
    "template_url_explainer": {
      "type": "string",
      "default": "Fetch the template from a public URL"
    },
    "text_template": { "type": "string", "default": "Text template" },
    "subject": {
      "additionalProperties": false,
      "properties": {
        "label": { "type": "string", "default": "Subject" },
        "placeholder": { "type": "string", "default": "" },
        "helper_text": { "type": "string", "default": "" }
      },
      "required": ["label", "placeholder", "helper_text"]
    },
    "template-language": {
      "additionalProperties": false,
      "properties": {
        "label": { "type": "string", "default": "Language" },
        "placeholder": { "type": "string", "default": "Default (Nunjucks)" },
        "helper_text": { "type": "string", "default": "" }
      },
      "required": ["label", "placeholder", "helper_text"]
    },
    "spinner": {
      "additionalProperties": false,
      "properties": {
        "loading_busy": { "type": "string", "default": "Loading" },
        "loading_error": { "type": "string", "default": "Failed to load" }
      },
      "required": ["loading_busy", "loading_error"]
    }
  },
  "required": [
    "cache",
    "cancel",
    "confirm",
    "create",
    "date",
    "date_created",
    "date_modified",
    "default",
    "delete",
    "delete_prompt",
    "description",
    "html_template",
    "template_clipboard",
    "template_clipboard_explainer",
    "template_default",
    "template_default_explainer",
    "template_url",
    "template_url_explainer",
    "text_template",
    "subject",
    "template-language",
    "spinner"
  ]
}

=== Foxy/foxy-elements/src/static/translations/email-template-form/en.json
{
  "cache": "Cache",
  "cancel": "Cancel",
  "confirm": "Confirm",
  "create": "Create",
  "date": "{{value, date}}",
  "date_created": "Created on",
  "date_modified": "Last updated",
  "default": "Default",
  "delete": "Delete",
  "delete_prompt": "This resource will be permanently removed. Are you sure?",
  "description": "Description",
  "html_template": "HTML template",
  "template_clipboard": "From clipboard",
  "template_clipboard_explainer": "Paste the template here to use it",
  "template_default": "Default",
  "template_default_explainer": "Use the default template",
  "template_url": "From URL",
  "template_url_explainer": "Fetch the template from a public URL",
  "text_template": "Text template",
  "subject": {
    "label": "Subject",
    "placeholder": "",
    "helper_text": ""
  },
  "template-language": {
    "label": "Language",
    "placeholder": "Default (Nunjucks)",
    "helper_text": ""
  },
  "spinner": {
    "loading_busy": "Loading",
    "loading_error": "Failed to load"
  }
}
