=== Foxy/foxy-elements/src/static/schemas/item-option-form.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "additionalProperties": false,
  "properties": {
    "name": {
      "additionalProperties": false,
      "properties": {
        "label": { "type": "string", "default": "Name" },
        "helper_text": { "type": "string", "default": "" },
        "placeholder": { "type": "string", "default": "Color" },
        "v8n_required": { "type": "string", "default": "Name is required" },
        "v8n_too_long": { "type": "string", "default": "Name mustn't exceed 100 characters" }
      },
      "required": ["label", "helper_text", "placeholder", "v8n_required", "v8n_too_long"]
    },
    "value": {
      "additionalProperties": false,
      "properties": {
        "label": { "type": "string", "default": "Value" },
        "helper_text": { "type": "string", "default": "" },
        "placeholder": { "type": "string", "default": "Red" },
        "v8n_required": { "type": "string", "default": "Value is required" },
        "v8n_too_long": { "type": "string", "default": "Value mustn't exceed 1024 characters" }
      },
      "required": ["label", "helper_text", "placeholder", "v8n_required", "v8n_too_long"]
    },
    "price-mod": {
      "additionalProperties": false,
      "properties": {
        "label": { "type": "string", "default": "Price" },
        "helper_text": { "type": "string", "default": "Same currency as item" },
        "placeholder": { "type": "string", "default": "10" }
      },
      "required": ["label", "helper_text", "placeholder"]
    },
    "weight-mod": {
      "additionalProperties": false,
      "properties": {
        "label": { "type": "string", "default": "Weight" },
        "helper_text": { "type": "string", "default": "Arbitrary units" },
        "placeholder": { "type": "string", "default": "5" }
      },
      "required": ["label", "helper_text", "placeholder"]
    },
    "timestamps": {
      "additionalProperties": false,
      "properties": {
        "date_created": { "type": "string", "default": "Created on" },
        "date_modified": { "type": "string", "default": "Last updated on" },
        "date": { "type": "string", "default": "{{value, date}}" }
      },
      "required": ["date_created", "date_modified", "date"]
    },
    "spinner": {
      "additionalProperties": false,
      "properties": {
        "refresh": { "type": "string", "default": "Refresh" },
        "loading_busy": { "type": "string", "default": "Loading" },
        "loading_error": { "type": "string", "default": "Unknown error" }
      },
      "required": ["refresh", "loading_busy", "loading_error"]
    },
    "delete": {
      "additionalProperties": false,
      "properties": {
        "delete": { "type": "string", "default": "Delete" },
        "cancel": { "type": "string", "default": "Cancel" },
        "delete_prompt": {
          "type": "string",
          "default": "Are you sure you'd like to remove this item option? You won't be able to bring it back."
        }
      },
      "required": ["delete", "cancel", "delete_prompt"]
    },
    "create": {
      "additionalProperties": false,
      "properties": { "create": { "type": "string", "default": "Create" } },
      "required": ["create"]
    }
  },
  "required": [
    "name",
    "value",
    "price-mod",
    "weight-mod",
    "timestamps",
    "spinner",
    "delete",
    "create"
  ]
}

=== Foxy/foxy-elements/src/static/translations/item-option-form/en.json
{
  "name": {
    "label": "Name",
    "helper_text": "",
    "placeholder": "Color",
    "v8n_required": "Name is required",
    "v8n_too_long": "Name mustn't exceed 100 characters"
  },
  "value": {
    "label": "Value",
    "helper_text": "",
    "placeholder": "Red",
    "v8n_required": "Value is required",
    "v8n_too_long": "Value mustn't exceed 1024 characters"
  },
  "price-mod": {
    "label": "Price",
    "helper_text": "Same currency as item",
    "placeholder": "10"
  },
  "weight-mod": {
    "label": "Weight",
    "helper_text": "Arbitrary units",
    "placeholder": "5"
  },
  "timestamps": {
    "date_created": "Created on",
    "date_modified": "Last updated on",
    "date": "{{value, date}}"
  },
  "spinner": {
    "refresh": "Refresh",
    "loading_busy": "Loading",
    "loading_error": "Unknown error"
  },
  "delete": {
    "delete": "Delete",
    "cancel": "Cancel",
    "delete_prompt": "Are you sure you'd like to remove this item option? You won't be able to bring it back."
  },
  "create": {
    "create": "Create"
  }
}
