=== Foxy/foxy-elements/src/static/schemas/items-form.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "additionalProperties": false,
  "properties": {
    "checkout": {
      "additionalProperties": false,
      "properties": {
        "buy": { "type": "string", "default": "Buy for {{value}}" },
        "subscribe_single_unit": {
          "type": "string",
          "default": "Subscribe for {{value}}/{{period}}"
        },
        "subscribe_muiltiple_units": {
          "type": "string",
          "default": "Subscribe for {{value}} {{period}}"
        }
      },
      "required": ["buy", "subscribe_single_unit", "subscribe_muiltiple_units"]
    },
    "freq": {
      "additionalProperties": false,
      "properties": {
        "just_this_once": { "type": "string", "default": "Just this once" },
        "day": { "type": "string", "default": "day" },
        "week": { "type": "string", "default": "week" },
        "month": { "type": "string", "default": "month" },
        "year": { "type": "string", "default": "year" }
      },
      "required": ["just_this_once", "day", "week", "month", "year"]
    },
    "error": {
      "additionalProperties": false,
      "properties": {
        "invalid_start_date": { "type": "string", "default": "Invalid start date." },
        "invalid_frequency": { "type": "string", "default": "Invalid frequency." },
        "invalid_end_date": { "type": "string", "default": "Invalid end date" },
        "frequency_options_must_be_array": {
          "type": "string",
          "default": "Frequency options must be an array."
        },
        "no_currency": { "type": "string", "default": "No currency available." }
      },
      "required": [
        "invalid_start_date",
        "invalid_frequency",
        "invalid_end_date",
        "frequency_options_must_be_array",
        "no_currency"
      ]
    },
    "item": {
      "additionalProperties": false,
      "properties": {
        "remove": { "type": "string", "default": "Remove" },
        "items": { "type": "string", "default": "{{quantity}} items" }
      },
      "required": ["remove", "items"]
    },
    "price": {
      "additionalProperties": false,
      "properties": { "total": { "type": "string", "default": "{{ amount }} total" } },
      "required": ["total"]
    }
  },
  "required": ["checkout", "freq", "error", "item", "price"]
}

=== Foxy/foxy-elements/src/static/translations/items-form/en.json
{
  "checkout": {
    "buy": "Buy for {{value}}",
    "subscribe_single_unit": "Subscribe for {{value}}/{{period}}",
    "subscribe_muiltiple_units": "Subscribe for {{value}} {{period}}"
  },
  "freq": {
    "just_this_once": "Just this once",
    "day": "day",
    "week": "week",
    "month": "month",
    "year": "year"
  },
  "error": {
    "invalid_start_date": "Invalid start date.",
    "invalid_frequency": "Invalid frequency.",
    "invalid_end_date": "Invalid end date",
    "frequency_options_must_be_array": "Frequency options must be an array.",
    "no_currency": "No currency available."
  },
  "item": {
    "remove": "Remove",
    "items": "{{quantity}} items"
  },
  "price": {
    "total": "{{ amount }} total"
  }
}
