=== Foxy/foxy-elements/src/static/schemas/transactions-table.json
{
  "additionalProperties": false,
  "properties": {
    "date": {
      "type": "string",
      "default": "{{value, date}}"
    },
    "price": {
      "type": "string",
      "default": "{{amount, price}}"
    },
    "receipt": {
      "type": "string",
      "default": "Receipt"
    },
    "transaction_approved": {
      "type": "string",
      "default": "Approved"
    },
    "transaction_authorized": {
      "type": "string",
      "default": "Authorized"
    },
    "transaction_captured": {
      "type": "string",
      "default": "Captured"
    },
    "transaction_completed": {
      "type": "string",
      "default": "Completed"
    },
    "transaction_declined": {
      "type": "string",
      "default": "Declined"
    },
    "transaction_pending": {
      "type": "string",
      "default": "Pending"
    },
    "transaction_refunded": {
      "type": "string",
      "default": "Refunded"
    },
    "transaction_rejected": {
      "type": "string",
      "default": "Rejected"
    },
    "transaction_summary": {
      "type": "string",
      "default": "{{most_expensive_item.name}}"
    },
    "transaction_summary_plural": {
      "type": "string",
      "default": "{{most_expensive_item.name}} and {{count}} more"
    },
    "transaction_verified": {
      "type": "string",
      "default": "Verified"
    },
    "transaction_voided": {
      "type": "string",
      "default": "Voided"
    },
    "spinner": {
      "additionalProperties": false,
      "properties": {
        "loading_busy": {
          "$ref": "spinner.json#/properties/loading_busy"
        },
        "loading_empty": {
          "$ref": "spinner.json#/properties/loading_empty"
        },
        "loading_error": {
          "$ref": "spinner.json#/properties/loading_error"
        }
      },
      "required": ["loading_busy", "loading_empty", "loading_error"]
    }
  },
  "required": [
    "date",
    "price",
    "receipt",
    "transaction_approved",
    "transaction_authorized",
    "transaction_captured",
    "transaction_completed",
    "transaction_declined",
    "transaction_pending",
    "transaction_refunded",
    "transaction_rejected",
    "transaction_summary",
    "transaction_summary_plural",
    "transaction_verified",
    "transaction_voided",
    "spinner"
  ],
  "$schema": "http://json-schema.org/draft-07/schema"
}

=== Foxy/foxy-elements/src/static/translations/transactions-table/en.json
{
  "date": "{{value, date}}",
  "price": "{{amount, price}}",
  "receipt": "Receipt",
  "transaction_approved": "Approved",
  "transaction_authorized": "Authorized",
  "transaction_captured": "Captured",
  "transaction_completed": "Completed",
  "transaction_declined": "Declined",
  "transaction_pending": "Pending",
  "transaction_refunded": "Refunded",
  "transaction_rejected": "Rejected",
  "transaction_summary": "{{most_expensive_item.name}}",
  "transaction_summary_plural": "{{most_expensive_item.name}} and {{count_minus_one}} more",
  "transaction_verified": "Verified",
  "transaction_voided": "Voided",
  "spinner": {
    "loading_busy": "Loading",
    "loading_empty": "No data",
    "loading_error": "Failed to load"
  }
}
